# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1boZjpQIf3j85_dAOVvdV5kWeeN-pAOr3
"""

import streamlit as st
import pandas as pd
import joblib

# 1. Load the model (This is all you need, no CSV required!)
model = joblib.load('titanic_model.pkl')

st.title("🚢 Titanic Survival Predictor")

# 2. Create the input fields for the user
pclass = st.selectbox("Passenger Class", [1, 2, 3])
sex = st.selectbox("Sex", ["male", "female"])
age = st.slider("Age", 0, 100, 30)
fare = st.number_input("Fare Paid", min_value=0.0, value=32.0)

# 3. Put the inputs into a format the model understands
input_data = pd.DataFrame([[pclass, sex, age, fare]], 
                          columns=['Pclass', 'Sex', 'Age', 'Fare'])

# 4. Make the prediction
if st.button("Predict"):
    prediction = model.predict(input_data)[0]
    if prediction == 1:
        st.success("The passenger is predicted to SURVIVE.")
    else:
        st.error("The passenger is predicted NOT to survive.")



